name: CICD

on:
  push:


jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t 02ahmalh/springboot-exmpel .
      - name: Publish image to docker hub
        run: docker push 02ahmalh/springboot-exmpel:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull 02ahmalh/springboot-exmpel:latest
      - name: Delete old container
        run: docker rm -f springboot-exmpel-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-exmpel-container 02ahmalh/springboot-exmpel
